# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true


#  datasource:
#    jdbc.driverClassName: com.mysql.jdbc.Driver
#    jdbc.url: jdbc:mysql://localhost:3306/myremember_me_security
#    jdbc.username: root
#    jdbc.password: 45Klapan
#    hibernate.dialect: org.hibernate.dialect.MySQLDialect
#    hibernate.show_sql: true
#    hibernate.format_sql: true


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG